FROM jboss/keycloak:10.0.2

#COPY simple-app-realm.json /opt/jboss/keycloak/imports/ppe-realm.json
#COPY standalone-ha.xml /opt/jboss/keycloak/standalone/configuration/standalone-ha.xml
#COPY keycloak.jks /opt/jboss/keycloak/standalone/configuration/application.keystore